version: '0.1.{build}'
image: Visual Studio 2015

platform:
  - x86

configuration:
  - Release
  - Debug

environment:
  CONERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: 7RjgqZ8QqJrG7ZlaTDbnK8irgdtjsDYLz

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg integrate install
  - vcpkg install gtest
  - nuget restore %APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%.sln

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\%APPVEYOR_PROJECT_NAME%.Tests.exe'